# Generated by Django 4.2.1 on 2025-03-24 09:20

from django.db import migrations, models
import django.db.models.deletion
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='telegram_users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(db_index=True, max_length=150, verbose_name='Текст')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='search.chat', verbose_name='Чат')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
