# Generated by Django 4.2.1 on 2025-03-27 09:50

from django.db import migrations, models
import django.db.models.deletion
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_users', '0001_initial'),
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(db_index=True, max_length=150, verbose_name='Текст')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='telegram_users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('message_link', models.URLField(verbose_name='Ссылка на сообщение')),
                ('message_id', models.PositiveIntegerField(verbose_name='ID сообщения в буферной группе')),
                ('is_reported', models.BooleanField(default=False, verbose_name='Отправлен')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.keyword', verbose_name='Ключевое слово')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='keyword',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='search.project', verbose_name='проект'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('chat_id', models.CharField(db_index=True, max_length=50)),
                ('chat_link', models.URLField(db_index=True, max_length=70)),
                ('name', models.CharField(max_length=130, verbose_name='Название')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='search.project', verbose_name='проект')),
                ('user_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='bots.userbot', verbose_name='Юзер бот')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
