# Generated by Django 4.2.1 on 2025-03-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='link',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_id',
            field=models.CharField(db_index=True, max_length=50),
            preserve_default=False,
        ),
    ]
