# Generated by Django 4.2.1 on 2025-03-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_link',
            field=models.URLField(db_index=True, max_length=70),
            preserve_default=False,
        ),
    ]
