# Generated by Django 4.2.1 on 2025-03-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lead_chat_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='ID группы для получения лидов'),
        ),
        migrations.AddField(
            model_name='project',
            name='lead_chat_link',
            field=models.URLField(blank=True, default=None, max_length=70, null=True, unique=True, verbose_name='Ссылка на группу для получения лидов'),
        ),
    ]
