# Generated by Django 4.2.1 on 2025-03-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_chat_chat_id_chat_chat_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='text',
            field=models.TextField(db_index=True, max_length=150, verbose_name='Текст'),
        ),
    ]
