# Generated by Django 4.2.1 on 2025-03-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_chat_link_chat_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Название'),
        ),
    ]
