# Generated by Django 4.2.1 on 2025-03-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_project_lead_chat_id_project_lead_chat_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lead_chat_name',
            field=models.CharField(blank=True, default=None, max_length=70, null=True, unique=True, verbose_name='Название группы для получения лидов'),
        ),
    ]
