# Generated by Django 4.2.1 on 2025-03-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_project_lead_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.chat', verbose_name='Чат'),
            preserve_default=False,
        ),
    ]
