# Generated by Django 4.2.1 on 2025-03-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_keyword_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_reported',
            field=models.BooleanField(default=False, verbose_name='Отправлен'),
        ),
    ]
