# Generated by Django 4.2.1 on 2025-03-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_match_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='message_id',
            field=models.PositiveIntegerField(db_index=True, unique=True, verbose_name='ID сообщения в буферной группе'),
        ),
        migrations.AlterField(
            model_name='match',
            name='message_link',
            field=models.URLField(unique=True, verbose_name='Ссылка на сообщение'),
        ),
    ]
