# Generated by Django 4.2.1 on 2025-03-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_match_message_id_alter_match_message_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='from_user_username',
            field=models.CharField(db_index=True, max_length=70, null=True, unique=True, verbose_name='Username автора сообщения'),
        ),
    ]
