# Generated by Django 4.2.1 on 2025-03-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_match_from_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='from_user_username',
            field=models.CharField(db_index=True, max_length=70, null=True, verbose_name='Username автора сообщения'),
        ),
    ]
