# Generated by Django 4.2.1 on 2025-03-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_chat_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_private',
        ),
    ]
