# Generated by Django 4.2.1 on 2025-03-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_alter_match_from_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приватный'),
        ),
    ]
