# Generated by Django 4.2.1 on 2025-03-28 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_remove_telegramuser_keywords_chat_id_and_more'),
        ('search', '0008_chat_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='message_id',
            field=models.PositiveIntegerField(db_index=True, verbose_name='ID сообщения в буферной группе'),
        ),
        migrations.AlterField(
            model_name='match',
            name='message_link',
            field=models.URLField(verbose_name='Ссылка на сообщение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='telegram_users.telegramuser', verbose_name='Пользователь'),
        ),
    ]
