# Generated by Django 4.2.1 on 2025-04-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_alter_match_message_id_alter_match_message_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='message_id',
            field=models.PositiveIntegerField(db_index=True, default=None, null=True, verbose_name='ID сообщения в буферной группе'),
        ),
    ]
