# Generated by Django 4.2.1 on 2025-03-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='search',
            field=models.BooleanField(default=True, verbose_name='Поиск'),
        ),
    ]
