# Generated by Django 4.2.1 on 2025-03-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0003_telegramuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(choices=[('Russian', 'Русский'), ('English', 'Английский'), ('Hebrew', 'Иврит')], db_index=True, default='Russian', max_length=10, verbose_name='Язык'),
        ),
    ]
