# Generated by Django 4.2.1 on 2025-03-25 11:17

from django.db import migrations, models
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBot',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Имя пользователя')),
                ('api_id', models.CharField(max_length=70, unique=True)),
                ('api_hash', models.CharField(max_length=70, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='Номер телефона')),
                ('session', models.FileField(unique=True, upload_to='userbots/sessions/', verbose_name='Файл сессии(.session)')),
                ('chats_count', models.PositiveIntegerField(default=0, verbose_name='Количество чатов')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
