# Generated by Django 4.2.1 on 2025-03-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='Телеграм ID'),
            preserve_default=False,
        ),
    ]
