# Generated by Django 4.2.1 on 2025-03-29 07:45

from django.db import migrations, models
import django.db.models.deletion
import web.db.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotKeyboard',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('language', models.CharField(choices=[('Russian', 'Русский'), ('English', 'Английский'), ('Hebrew', 'Иврит')], db_index=True, default='Russian', max_length=10, verbose_name='Язык')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Название')),
                ('type', models.CharField(choices=[('Reply', 'Reply'), ('Inline', 'Inline')], default='Inline', max_length=15, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Клавиатура',
                'verbose_name_plural': 'Клавиатуры бота',
            },
        ),
        migrations.CreateModel(
            name='BotKeyboardButton',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('text', models.CharField(max_length=150, verbose_name='Текст')),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='bots.botkeyboard', verbose_name='Кнопки')),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки бота',
            },
        ),
        migrations.AddConstraint(
            model_name='botkeyboardbutton',
            constraint=models.UniqueConstraint(fields=('text', 'keyboard'), name='unique_button_text_per_keyboard'),
        ),
    ]
