# Generated by Django 4.2.1 on 2025-03-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_userbot_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbot',
            name='session',
        ),
        migrations.AddField(
            model_name='userbot',
            name='session_1',
            field=models.FileField(unique=True, upload_to='userbots/sessions/1/', verbose_name='Файл сессии 1(.session)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbot',
            name='session_2',
            field=models.FileField(unique=True, upload_to='userbots/sessions/2/', verbose_name='Файл сессии 2(.session)'),
            preserve_default=False,
        ),
    ]
