# Generated by Django 4.2.1 on 2025-03-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_botkeyboard_slug_alter_botkeyboard_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='botkeyboardbutton',
            name='unique_button_text_per_keyboard',
        ),
        migrations.RemoveField(
            model_name='botkeyboard',
            name='language',
        ),
        migrations.RemoveField(
            model_name='botkeyboardbutton',
            name='name',
        ),
        migrations.RemoveField(
            model_name='botkeyboardbutton',
            name='text',
        ),
        migrations.AddField(
            model_name='botkeyboardbutton',
            name='en_text',
            field=models.CharField(max_length=150, verbose_name='Текст на ангилйском 🇺🇸'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botkeyboardbutton',
            name='he_text',
            field=models.CharField(max_length=150, verbose_name='Текст на иврите 🇮🇱'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botkeyboardbutton',
            name='ru_text',
            field=models.CharField(max_length=150, verbose_name='Текст на русском 🇷🇺'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='botkeyboardbutton',
            constraint=models.UniqueConstraint(fields=('ru_text', 'en_text', 'he_text', 'keyboard'), name='unique_button_text_per_keyboard'),
        ),
    ]
