# Generated by Django 4.2.1 on 2025-03-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_remove_botkeyboardbutton_unique_button_text_per_keyboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botkeyboardbutton',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
