# Generated by Django 4.2.1 on 2025-03-30 05:46

from django.db import migrations
import web.apps.bots.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_englishbottexts_hebrewbottexts_russianbottexts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='englishbottexts',
            options={'verbose_name': 'Тексты бота на английском', 'verbose_name_plural': 'Тексты бота на английском'},
        ),
        migrations.AlterModelOptions(
            name='hebrewbottexts',
            options={'verbose_name': 'Тексты бота на иврите', 'verbose_name_plural': 'Тексты бота на иврите'},
        ),
        migrations.AlterModelOptions(
            name='russianbottexts',
            options={'verbose_name': 'Тексты бота на русском', 'verbose_name_plural': 'Тексты бота на русском'},
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='choice_language_message_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст изменения языка'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='choice_language_message_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст изменения языка'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='choice_language_message_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст изменения языка'),
        ),
    ]
