# Generated by Django 4.2.1 on 2025-03-30 06:23

from django.db import migrations
import web.apps.bots.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_alter_englishbottexts_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botkeyboard',
            name='type',
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='keyword_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст ошибки "Ключевое слово уже добавлено в проект"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='keyword_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст ошибки "Ключевое слово уже добавлено в проект"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='keyword_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст ошибки "Ключевое слово уже добавлено в проект"'),
        ),
    ]
