# Generated by Django 4.2.1 on 2025-03-30 06:26

from django.db import migrations
import web.apps.bots.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_remove_botkeyboard_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishbottexts',
            name='permission_denied_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст "Отказано в доступе ❌"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hebrewbottexts',
            name='permission_denied_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст "Отказано в доступе ❌"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='russianbottexts',
            name='permission_denied_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст "Отказано в доступе ❌"'),
            preserve_default=False,
        ),
    ]
