# Generated by Django 4.2.1 on 2025-03-30 07:04

from django.db import migrations
import web.apps.bots.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_englishbottexts_permission_denied_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishbottexts',
            name='project_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст ошибки "Проект уже добавлен"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hebrewbottexts',
            name='project_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст ошибки "Проект уже добавлен"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='russianbottexts',
            name='project_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст ошибки "Проект уже добавлен"'),
            preserve_default=False,
        ),
    ]
