# Generated by Django 4.2.1 on 2025-03-30 07:43

from django.db import migrations
import web.apps.bots.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0010_englishbottexts_project_exists_error_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishbottexts',
            name='analytic_match_report_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст рассылки аналитики совпадений'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='englishbottexts',
            name='match_report_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст рассылки совпадения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hebrewbottexts',
            name='analytic_match_report_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст рассылки аналитики совпадений'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hebrewbottexts',
            name='match_report_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст рассылки совпадения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='russianbottexts',
            name='analytic_match_report_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст рассылки аналитики совпадений'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='russianbottexts',
            name='match_report_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст рассылки совпадения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='add_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Добавить ➕"'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='ask_send_chat_link_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст просьбы отправить ссылку чата при добавлении'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='ask_send_keyword_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст просьбы отправить ключевое слово при добавлении'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='ask_send_project_name_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст просьбы отправить название проекта при добавлении'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='back_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Назад 🔙"'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='cancel_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст после нажатии кнопки "Отмена ❌"'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='chat_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки "Чат уже добавлен"'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='chat_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст на странице чата'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='chats_list_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Список чатов 🗂"'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='chats_list_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст на странице списка чатов'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='choice_action_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст "Выберите действие"'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='choice_language_message_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст изменения языка'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='delete_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Удалить 🗑"'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='join_chat_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки присоединения к чату'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='keyword_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки "Ключевое слово уже добавлено в проект"'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='keyword_max_length_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки превышения максимальной длинны ключевого слова'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='keyword_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст на странице ключевого слова'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='keywords_list_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Список ключевых слов 🗂"'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='keywords_list_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст на странице списка ключевых слов'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='lead_chat_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "📥 Группа для получения лидов 📥"'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='lead_chat_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки "Этот чат уже добавлен другим пользователем"'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='no_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Нет"'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='permission_denied_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст "Отказано в доступе ❌"'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='project_chats_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "⚙️ Настройка групп для отслеживания ⚙️"'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='project_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки "Проект уже добавлен"'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='project_keywords_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "💬 Ключевые слова  💬"'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='project_name_max_length_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки превышения максимальной длинны названия проекта'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='projects_list_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Список проектов 🗂"'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='projects_list_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст на странице списка проектов'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='search_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст сообщения поиска'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='successful_add_chat_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного добавления чата'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='successful_add_keyword_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного добавления ключевого слова'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='successful_add_lead_chat_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного добавления чата для получения лидов'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='successful_add_project_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного добавления проекта'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='successful_rm_chat_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного удаления чата'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='successful_rm_keyword_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного удаления ключевого слова'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='successful_rm_lead_chat_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного удаления чата для получения лидов'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='successful_rm_project_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного удаления проекта'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='sure_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст перед удалением ("Вы уверены?")'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='turn_off_search_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки выключения поиска 🔎'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='turn_on_search_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки включения поиска 🔎'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='wait_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ожидания ("Подожите . . .")'),
        ),
        migrations.AlterField(
            model_name='englishbottexts',
            name='yes_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Да"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='add_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Добавить ➕"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='ask_send_chat_link_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст просьбы отправить ссылку чата при добавлении'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='ask_send_keyword_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст просьбы отправить ключевое слово при добавлении'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='ask_send_project_name_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст просьбы отправить название проекта при добавлении'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='back_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Назад 🔙"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='cancel_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст после нажатии кнопки "Отмена ❌"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='chat_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки "Чат уже добавлен"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='chat_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст на странице чата'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='chats_list_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Список чатов 🗂"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='chats_list_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст на странице списка чатов'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='choice_action_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст "Выберите действие"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='choice_language_message_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст изменения языка'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='delete_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Удалить 🗑"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='join_chat_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки присоединения к чату'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='keyword_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки "Ключевое слово уже добавлено в проект"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='keyword_max_length_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки превышения максимальной длинны ключевого слова'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='keyword_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст на странице ключевого слова'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='keywords_list_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Список ключевых слов 🗂"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='keywords_list_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст на странице списка ключевых слов'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='lead_chat_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "📥 Группа для получения лидов 📥"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='lead_chat_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки "Этот чат уже добавлен другим пользователем"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='no_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Нет"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='permission_denied_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст "Отказано в доступе ❌"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='project_chats_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "⚙️ Настройка групп для отслеживания ⚙️"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='project_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки "Проект уже добавлен"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='project_keywords_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "💬 Ключевые слова  💬"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='project_name_max_length_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки превышения максимальной длинны названия проекта'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='projects_list_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Список проектов 🗂"'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='projects_list_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст на странице списка проектов'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='search_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст сообщения поиска'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='successful_add_chat_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного добавления чата'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='successful_add_keyword_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного добавления ключевого слова'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='successful_add_lead_chat_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного добавления чата для получения лидов'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='successful_add_project_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного добавления проекта'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='successful_rm_chat_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного удаления чата'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='successful_rm_keyword_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного удаления ключевого слова'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='successful_rm_lead_chat_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного удаления чата для получения лидов'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='successful_rm_project_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного удаления проекта'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='sure_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст перед удалением ("Вы уверены?")'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='turn_off_search_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки выключения поиска 🔎'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='turn_on_search_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки включения поиска 🔎'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='wait_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ожидания ("Подожите . . .")'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='yes_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Да"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='add_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Добавить ➕"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='ask_send_chat_link_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст просьбы отправить ссылку чата при добавлении'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='ask_send_keyword_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст просьбы отправить ключевое слово при добавлении'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='ask_send_project_name_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст просьбы отправить название проекта при добавлении'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='back_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Назад 🔙"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='cancel_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст после нажатии кнопки "Отмена ❌"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='chat_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки "Чат уже добавлен"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='chat_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст на странице чата'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='chats_list_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Список чатов 🗂"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='chats_list_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст на странице списка чатов'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='choice_action_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст "Выберите действие"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='choice_language_message_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст изменения языка'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='delete_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Удалить 🗑"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='join_chat_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки присоединения к чату'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='keyword_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки "Ключевое слово уже добавлено в проект"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='keyword_max_length_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки превышения максимальной длинны ключевого слова'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='keyword_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст на странице ключевого слова'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='keywords_list_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Список ключевых слов 🗂"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='keywords_list_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст на странице списка ключевых слов'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='lead_chat_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "📥 Группа для получения лидов 📥"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='lead_chat_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки "Этот чат уже добавлен другим пользователем"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='no_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Нет"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='permission_denied_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст "Отказано в доступе ❌"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='project_chats_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "⚙️ Настройка групп для отслеживания ⚙️"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='project_exists_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки "Проект уже добавлен"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='project_keywords_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "💬 Ключевые слова  💬"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='project_name_max_length_error_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ошибки превышения максимальной длинны названия проекта'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='projects_list_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Список проектов 🗂"'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='projects_list_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст на странице списка проектов'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='search_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст сообщения поиска'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='successful_add_chat_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного добавления чата'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='successful_add_keyword_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного добавления ключевого слова'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='successful_add_lead_chat_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного добавления чата для получения лидов'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='successful_add_project_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного добавления проекта'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='successful_rm_chat_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного удаления чата'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='successful_rm_keyword_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного удаления ключевого слова'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='successful_rm_lead_chat_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного удаления чата для получения лидов'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='successful_rm_project_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст успешного удаления проекта'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='sure_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст перед удалением ("Вы уверены?")'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='turn_off_search_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки выключения поиска 🔎'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='turn_on_search_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки включения поиска 🔎'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='wait_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст ожидания ("Подожите . . .")'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='yes_button_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст кнопки "Да"'),
        ),
    ]
