# Generated by Django 4.2.1 on 2025-03-30 07:50

from django.db import migrations
import web.apps.bots.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_englishbottexts_analytic_match_report_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishbottexts',
            name='analytic_match_report_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст рассылки аналитики совпадений'),
        ),
        migrations.AlterField(
            model_name='hebrewbottexts',
            name='analytic_match_report_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст рассылки аналитики совпадений'),
        ),
        migrations.AlterField(
            model_name='russianbottexts',
            name='analytic_match_report_text',
            field=web.apps.bots.model_mixins.TelegramMessageCharField(max_length=200, verbose_name='Текст рассылки аналитики совпадений'),
        ),
    ]
