# Generated by Django 4.2.1 on 2025-03-30 08:01

from django.db import migrations
import web.apps.bots.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0012_alter_englishbottexts_analytic_match_report_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishbottexts',
            name='share_request_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст рассылки с просьбой поделиться сервисом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hebrewbottexts',
            name='share_request_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст рассылки с просьбой поделиться сервисом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='russianbottexts',
            name='share_request_text',
            field=web.apps.bots.model_mixins.TelegramMessageTextField(max_length=4096, verbose_name='Текст рассылки с просьбой поделиться сервисом'),
            preserve_default=False,
        ),
    ]
