# Generated by Django 4.2.1 on 2025-04-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0013_englishbottexts_share_request_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbot',
            name='session_1',
        ),
        migrations.RemoveField(
            model_name='userbot',
            name='session_2',
        ),
        migrations.AddField(
            model_name='userbot',
            name='session',
            field=models.FileField(default=1, unique=True, upload_to='userbots/sessions/', verbose_name='Файл сессии 1(.session)'),
            preserve_default=False,
        ),
    ]
