# Generated by Django 4.2.1 on 2025-04-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0014_remove_userbot_session_1_remove_userbot_session_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbot',
            name='session',
        ),
        migrations.AddField(
            model_name='userbot',
            name='session_string',
            field=models.CharField(default='1', max_length=100, unique=True, verbose_name='Строка сессии'),
        ),
    ]
