# Generated by Django 4.2.1 on 2025-04-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0015_remove_userbot_session_userbot_session_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbot',
            name='session_string',
            field=models.TextField(default='1', unique=True, verbose_name='Строка сессии'),
        ),
    ]
