# Generated by Django 4.2.1 on 2025-04-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0016_alter_userbot_session_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='session',
            field=models.FileField(default='1', unique=True, upload_to='', verbose_name='Файл сессии(.session)'),
        ),
    ]
