# Generated by Django 4.2.1 on 2025-04-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0017_userbot_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbot',
            name='session',
            field=models.FileField(default=None, null=True, unique=True, upload_to='userbots/sessions/', verbose_name='Файл сессии telethon (.session)'),
        ),
        migrations.AlterField(
            model_name='userbot',
            name='session_string',
            field=models.TextField(default=None, null=True, unique=True, verbose_name='Строка сессии(pyrogram)'),
        ),
    ]
