# Generated by Django 4.2.1 on 2025-04-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0018_alter_userbot_session_alter_userbot_session_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbot',
            old_name='session_string',
            new_name='pyrogram_session_string',
        ),
        migrations.RemoveField(
            model_name='userbot',
            name='session',
        ),
        migrations.RemoveField(
            model_name='userbot',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='userbot',
            name='telethon_session_string',
            field=models.TextField(default=None, null=True, unique=True, verbose_name='Строка сессии(telethon)'),
        ),
    ]
